FROM  italiangrid/build-centos7

run yum -y install pkgconfig \
  globus-gssapi-gsi-devel \
  globus-gss-assist-devel \
  gsoap-devel \
  CGSI-gSOAP-devel \
  voms
user build
add Makefile ./storm-info-provider.spec.in /home/build/
workdir /home/build

cmd /bin/bash -c make
